GET http://localhost:3000/favorecido/33

###

POST http://localhost:3000/favorecido
Content-Type: application/json

{
  "favorecido": {
    "name": "Jhon Conor",
    "doc": "47206027032",
    "email": "jhon.conor@gmail.com",
    "cod_banco": "001",
    "agencia": "01234",
    "agencia_digito": "1",
    "conta": "00012345",
    "conta_digito": 1,
    "status": "Rascunho"
  }
}

###


PUT http://localhost:3000/favorecido/39
Content-Type: application/json

{
  "favorecido": {
    "email": "jhon.conor2@gmail.com",
    "cod_banco": "001"
  }
}

###
DELETE http://localhost:3000/favorecido/35

###
DELETE http://localhost:3000/favorecido
Content-Type: application/json

{
  "favorecidos": [
    1,
    "2",
    3,
    null,
    "gatinhos",
    5,
    33
  ]
}

###


