GET http://localhost:3000/payee/33

###

POST http://localhost:3000/payee
Content-Type: application/json

{
  "payee": {

  }
}

###


PUT http://localhost:3000/payee/null
Content-Type: application/json

{
  "payee": {
    "email": "jhon.conor2@gmail.com",
    "cod_bank": "001",
    "doc": "1781.134.390-80"
  }
}

###
DELETE http://localhost:3000/payee/35

###
DELETE http://localhost:3000/payee
Content-Type: application/json

{
  "payees": [
    1,
    "2",
    3,
    null,
    "gatinhos",
    5,
    33
  ]
}

###


