name: Testes E2E

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    name: Rodar testes E2E
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'test'
    steps:
      - name: Puxar o código do commit
        uses: actions/checkout@v2

      - name: Instalar o Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Instalar Dependências
        uses: CultureHQ/actions-yarn@master
        with:
          args: install

      - name: Rodar testes
        uses: CultureHQ/actions-yarn@master
        with:
          args: test

      - name: Rodar testes
        uses: CultureHQ/actions-yarn@master
        with:
          args: test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: reports/coverage/lcov.info
